services:
    wordwars.admin:
        class: WordWarsBundle\Admin\WordWarsAdmin
        tags:
            - { name: sonata.admin, manager_type: orm, group: "Content", label: "WW" }
        arguments:
            - ~
            - WordWarsBundle\Entity\WordWar
            - ~
        calls:
            - [ setTranslationDomain, [WordWarsBundle]]
        public: true
