word_wars_new:
    path:     /wordwars/new
    defaults: { _controller: WordWarsBundle:WordWars:new }

word_wars_in_progress:
    path:     /wordwars/in_progress/{id}
    defaults: { _controller: WordWarsBundle:WordWars:inProgress }
    requirements:
        id: \d+

save_my_ww_words:
    path:     /wordwars/in_progress/save
    defaults: { _controller: WordWarsBundle:WordWars:save}
    requirements:
        _method: POST
    options:
        expose: true

word_war_ended:
    path:     /wordwars/in_progress/{id}/end
    defaults: { _controller: WordWarsBundle:WordWars:wwEnded }
    requirements:
        id: \d+
