my_stats_daily:
    path:     /mystats/month
    defaults: { _controller: MyStatsBundle:MyStats:dailyStats }

my_stats_ww:
    path:     /mystats/ww
    defaults: { _controller: MyStatsBundle:MyStats:wwStats }

my_stats_nano:
    path:     /mystats/nanos
    defaults: { _controller: MyStatsBundle:MyNanos:myNanos }

my_stats_archives:
    path:     /mystats/archives/{page}
    defaults:
        _controller: MyStatsBundle:Archives:myArchives
        page: 1
    requirements:
        page: \d*

my_stats_filter_archives:
    path:     /mystats/archives/filter
    defaults: { _controller: MyStatsBundle:Archives:filter }
    requirements:
        _method: POST
    options:
        expose: true
