my_stats:
    resource: "@MyStatsBundle/Resources/config/routing.yml"
    prefix:   /{_locale}
    requirements:
        _locale: fr|en

word_wars:
    resource: "@WordWarsBundle/Resources/config/routing.yml"
    prefix:   /{_locale}
    requirements:
        _locale: fr|en

user:
    resource: "@UserBundle/Resources/config/routing.yml"
    prefix:   /

my_words:
    resource: "@MyWordsBundle/Resources/config/routing.yml"
    prefix:   /{_locale}
    requirements:
        _locale: fr|en

core:
    resource: "@CoreBundle/Resources/config/routing.yml"
    prefix:   /{_locale}
    defaults:
        _locale: fr
    requirements:
        _locale: fr|en

fos_user_security:
    resource: "@FOSUserBundle/Resources/config/routing/security.xml"
    prefix: /{_locale}
    requirements:
        _locale: fr|en

fos_user_profile:
    resource: "@FOSUserBundle/Resources/config/routing/profile.xml"
    prefix: /{_locale}/profile
    requirements:
        _locale: fr|en

fos_user_register:
    resource: "@FOSUserBundle/Resources/config/routing/registration.xml"
    prefix: /{_locale}/register
    requirements:
        _locale: fr|en

fos_user_resetting:
    resource: "@FOSUserBundle/Resources/config/routing/resetting.xml"
    prefix: /{_locale}/resetting
    requirements:
        _locale: fr|en

fos_user_change_password:
    resource: "@FOSUserBundle/Resources/config/routing/change_password.xml"
    prefix: /{_locale}/profile
    requirements:
        _locale: fr|en

fos_js_routing:
    resource: "@FOSJsRoutingBundle/Resources/config/routing/routing.xml"

admin_area:
    resource: "@SonataAdminBundle/Resources/config/routing/sonata_admin.xml"
    prefix: /admin

_admin:
    resource: '@SonataAdminBundle/Resources/config/routing/sonata_admin.xml'
    prefix: /admin

_sonata_admin:
    resource: .
    type: sonata_admin
    prefix: /admin
